---
- name: Install packages
  hosts: localhost
  connection: localhost
  become: true
  tags: packages
  gather_facts: true
  tasks:

   - name: Update apt cache
     ansible.builtin.apt:
      update_cache: true
     when: ansible_facts['os_family'] == "Debian"
     changed_when: false

   - name: Install dev related packages
     ansible.builtin.package:
      state: present
      name:
       - git
       - golang
       - lazygit
       - shellcheck
       - shfmt
       - podman

   - name: Standard utilities
     ansible.builtin.apt:
      state: present
      name:
       - tree-sitter-cli
       - ripgrep
       - fd-find
       - wireguard-tools
       - wl-clipboard
       - kitty
       - stow
       - starship
       - tealdeer
       - fzf
       - keychain
       - micro
       - tree
       - syncthingtray-kde-plasma
       - restic
       - apprise

   - name: Remove any packages that we'd rather have flatpaks of
     ansible.builtin.package:
      state: absent
      name:
       - kate

- name: Flatpak Packages Setup
  hosts: localhost
  become: true
  gather_facts: false
  tags: flatpak
  tasks:

   - name: Package installs
     ansible.builtin.package:
      name:
       - flatpak
       - plasma-discover-backend-flatpak
      state: present

- name: Flatpak User Setup
  hosts: localhost
  become: false
  tags: flatpak, flatpak_apps
  gather_facts: false
  tasks:

    - name: Flathub repo setup for local user
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        state: present
        method: user

    - name: Install Flatpak packages from Flathub in the current user profile
      community.general.flatpak:
       state: present
       remote: flathub
       method: user
       name:
        - it.mijorus.gearlever
        - org.gnome.World.PikaBackup
        - org.kde.kate
        - io.podman_desktop.PodmanDesktop
        - md.obsidian.Obsidian
        - org.qbittorrent.qBittorrent

- name: Incus Client Setup
  hosts: localhost
  become: true
  tags: incus
  gather_facts: true
  tasks:

   - name: Install python3-debian
     ansible.builtin.apt:
       name: python3-debian
       update_cache: true
       state: present

   - name: Add Deb822 Repo
     ansible.builtin.deb822_repository:
       name: zabbly-incus-stable
       types: deb
       uris: https://pkgs.zabbly.com/incus/stable
       suites: '{{ ansible_distribution_release }}'
       components: main
       signed_by: https://pkgs.zabbly.com/key.asc

   - name: Install Incus client
     ansible.builtin.apt:
       name: incus-client
       state: present
       update_cache: true

- name: OpenTofu Setup
  hosts: localhost
  become: false
  tags: opentofu, terraform
  gather_facts: true
  tasks:

   - name: Download OpenTofu archive
     ansible.builtin.get_url:
      checksum: sha256:dc0ad16a42b3bfb5f3ceff3dcd5e9cd4c55271fae9f4bfe611749ff8ae6ec23c
      dest: $HOME/Downloads
      url: https://github.com/opentofu/opentofu/releases/download/v1.12.2/tofu_1.12.2_linux_amd64.zip

   - name: Unpack OpenTofu binary
     ansible.builtin.unarchive:
      remote_src: true
      mode: u=rwx,go=rx
      include: tofu
      dest: $HOME/.local/bin
      src: $HOME/Downloads/tofu_1.12.2_linux_amd64.zip
